# Configure app
DEBUG = True
SECRET_KEY = 'REPLACE THIS WITH SOMETHING SUPER SECRET FOR PRODUCTION'
# DB Settins - change for production
POSTGRES_USER = 'USER'
POSTGRES_PW = 'PASSWORD'
POSTGRES_URL = 'localhost'
POSTGRES_PORT = '5432'
POSTGRES_DB = 'DB_NAME'
DB_URL = 'postgresql+psycopg2://{user}:{pw}@{url}:{port}/{db}'.format(user=POSTGRES_USER, pw=POSTGRES_PW, url=POSTGRES_URL, port=POSTGRES_PORT,db=POSTGRES_DB)
SQLALCHEMY_DATABASE_URI = DB_URL
SQLALCHEMY_TRACK_MODIFICATIONS = False

JSON_SORT_KEYS = False
